### ISSUE TITLE
Table data does not appear on initial load

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/pulse#49]
1. Go to https://cdspulse.azurewebsites.net/
2. Observe that the table data does not render: 
![image](https://user-images.githubusercontent.com/3474250/40241077-137b48fc-5a88-11e8-9258-b8e65c0a1828.png)
3. Hit refresh, observe the data renders: 
![image](https://user-images.githubusercontent.com/3474250/40241148-4188fa78-5a88-11e8-9e37-6bcdd23421c0.png)

Expected that the data would render on first load.

**Comment by buckley-w-david** [comment]
Unfortunately a bit more complicated than it just not loading the first time, it's seemingly random.

https://cdspulse.azurewebsites.net/data/hosts/https.json is throwing 500 errors seemingly at random due to the DB cursor for the query made to pull the data not existing when it's attempting to read from it.. Cannot reproduce the problem locally even when connecting to the same DB.

Investigating.

**Comment by buckley-w-david** [comment]
Interestingly, I seem to be unable to reproduce the problem right now. Possibly related to the fact that the DB contains significantly less data than it did when this problem was reported.

**Comment by sidewalkballet** [comment]
Closing as unable to repro and the db is back at the size it was before.
