### ISSUE TITLE
Footer is not sticking to bottom of page on IE 

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/pulse#79]
On IE

On load:
![image](https://user-images.githubusercontent.com/3474250/40445837-50d86150-5e9b-11e8-9bb3-733b03ebf0bc.png)

Scroll a bit: 
![image](https://user-images.githubusercontent.com/3474250/40445806-3579b8f0-5e9b-11e8-986f-fdac7233a710.png)

**Comment by obrien-j** [comment]
@lchski You mentioned you'd seen this before. Easy fix?

**Comment by lchski** [comment]
It’s a flexbox issue. Try changing `.flex-1` to `flex: 1 0 auto` instead of just `flex: 1`, per https://stackoverflow.com/questions/21600345/flexbox-and-internet-explorer-11-displayflex-in-html.

I tested it quickly in the IE 11 inspector and it works there, but should verify it doesn’t mess up other browsers. Also I’m not sure where `.flex-1` is declared, or I’d have done a PR 😛

**Comment by evadb** [comment]
thank you @lchski !

**Comment by evadb** [comment]
https://github.com/cds-snc/pulse/pull/123 

late but fixed
